#include <Bonobo.idl>

module GNOME
{
	interface RhythmboxShell : Bonobo::Unknown
	{
		void handleFile (in string uri);

		void addToLibrary (in string uri);

		void grabFocus ();

		void quit ();
	};
};

