#include <Bonobo.idl>

/* arch-tag: Rhythmbox Bonobo interface definition
 */

module GNOME
{
	interface Rhythmbox : Bonobo::Unknown
	{
		void addToLibrary (in string uri);

		void handleFile (in string uri);

		void grabFocus ();

		string getPlayingTitle ();
		string getPlayingPath ();
	
		void quit ();
	};
};

