#!/usr/bin/perl -w
#
#  Gnumeric
#
#  Copyright (C) 2001 Morten Welinder.
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of the
#  License, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this library; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#  Author: Morten Welinder <terra@gnome.org>

use strict;

my $exitcode = 0;

die "$0: must be run from top-level directory.\n"
    unless (-r "configure.in" || -r "configure.ac") && -r 'ChangeLog';

my %exceptions =
    (
     );


my @files;
{
    local (*FIND);
    open (*FIND, "find . '(' -name \*.glade -type f -print ')' -o '(' -type d '(' -name CVS -o -name intl -o -name macros ')' -prune ')' |")
	or die "$0: cannot execute find: $!\n";
    foreach my $filename (<FIND>) {
	chomp $filename;
	$filename =~ s|^\./||;
	next if $exceptions{$filename};
	push @files, $filename;
    }
    close (*FIND);
}


FILE:
    foreach my $filename (@files) {
	local (*GREP);
	open (*GREP, "grep -c '^  <property name=\"visible\">True</property>' '$filename' /dev/null 2>/dev/null |")
	    or die "$0: cannot execute grep: $!\n";
	while (<GREP>) {
	    chomp;
	    last if m|^/dev/null:|;
	    if (!/:0$/) {
		print STDERR "File `$filename' sets the visible property to True.\n";
		$exitcode = 1;
		next FILE;
	    }
	}
	close (*GREP);
    }

exit $exitcode;
