const char *mpris_iface_name = "org.freedesktop.MediaPlayer";

const char *mpris_root_spec =
	"<node name='/Root_Node'>"
	"  <interface name='org.freedesktop.MediaPlayer'>"
	"    <method name='Identity'>"
	"      <arg direction='out' type='s' name='Identity' />"
	"    </method>"
	"    <method name='Quit' />"
	"    <method name='MprisVersion'>"
	"      <arg direction='out' type='(qq)' name='MprisVersion' />"
	"    </method>"
	"  </interface>"
	"</node>";

/* obviously incomplete */
const char *mpris_tracklist_spec =
	"<node name='/TrackList_Node'>"
	"  <interface name='org.freedesktop.MediaPlayer'>"
	"  </interface>"
	"</node>";

const char *mpris_player_spec =
	"<node name='/Player_Node'>"
	"  <interface name='org.freedesktop.MediaPlayer'>"
	"    <method name='Next' />"
	"    <method name='Prev' />"
	"    <method name='Pause' />"
	"    <method name='Stop' />"
	"    <method name='Play' />"
	"    <method name='PlayPause' />"
	"    <method name='Repeat' >"
	"      <arg direction='in' type='b' name='State' />"
	"    </method>"
	"    <method name='GetStatus'>"
	"      <arg direction='out' type='(iiii)' name='Status' />"
	"    </method>"
	"    <method name='GetMetadata'>"
	"      <arg direction='out' type='a{sv}' name='Metadata' />"
	"    </method>"
	"    <method name='GetCaps'>"
	"      <arg direction='out' type='i' name='Capabilities' />"
	"    </method>"
	"    <method name='VolumeSet'>"
	"      <arg direction='in' type='i' name='Volume' />"
	"    </method>"
	"    <method name='VolumeGet'>"
	"      <arg direction='out' type='i' name='Volume' />"
	"    </method>"
	"    <method name='PositionSet'>"
	"      <arg direction='in' type='i' name='Position' />"
	"    </method>"
	"    <method name='PositionGet'>"
	"      <arg direction='out' type='i' name='Position' />"
	"    </method>"
	"    <signal name='TrackChange'>"
	"      <arg name='Metadata' type='a{sv}' />"
	"    </signal>"
	"    <signal name='StatusChange'>"
	"      <arg name='Status' type='(iiii)'/>"
	"    </signal>"
	"    <signal name='CapsChange'>"
	"      <arg name='Capabilities' type='i' />"
	"    </signal>"
	"  </interface>"
	"</node>";
